In [ ]:
pip install opencv-python Pillow tensorflow


In [1]:
import tkinter as tk
from PIL import Image, ImageTk
import mediapipe as mp
import pandas as pd
import numpy as np
import cv2
import tensorflow as tf
from tensorflow import keras

class YogifyApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Yogify Pose")
        self.root.minsize(900, 700)
        self.root.iconbitmap("C:\\aryaaa\\arya's model(2)\\deploying model\\icon.ico")
        self.root.configure(bg="teal")
        self.model_To_Select = "None"

        # Create a Canvas widget
        self.canvas = tk.Canvas(root, bg="teal", highlightthickness=0)
        self.canvas.pack(side="left", fill="both", expand=True)

        # Create a Scrollbar widget and attach it to the Canvas
        self.scrollbar = tk.Scrollbar(root, command=self.canvas.yview)
        self.scrollbar.pack(side="right", fill="y")

        # Configure the Canvas to scroll with the Scrollbar
        self.canvas.configure(yscrollcommand=self.scrollbar.set)

        # Create a Frame inside the Canvas
        self.frame = tk.Frame(self.canvas, bg="teal")
        self.canvas.create_window((0, 0), window=self.frame, anchor="nw")

        # widgets
        self.label1 = tk.Label(self.frame, text="Welcome to YogifyPose – Your Ultimate Yoga Pose Companion!",
                               font=("Times New Roman", 42, "bold"), bg="teal", foreground="white")
        self.label1.grid(row=0, column=0, columnspan=7, pady=(80, 130))

        self.label2 = tk.Label(self.frame, text="Embark on a journey of self-discovery and wellness with YogifyPose, "
                                                "the cutting-edge real-time yoga pose detection website."
                                                "Whether you are a seasoned yogi or just starting your yoga journey,"
                                                "YogifyPose is here to enhance your practice, bringing mindfulness and technology together.",
                               font=("Times New Roman", 20, "bold"), bg="teal", foreground="white", wraplength=1100,
                               justify='left')
        self.label2.grid(row=1, column=0, sticky="w", padx=40, pady=(10, 150))

        img = Image.open("C:\\aryaaa\\arya's model(2)\\deploying model\\poses image1.png")
        resized_img = img.resize((730, 300))
        self.img = ImageTk.PhotoImage(resized_img)
        img_label = tk.Label(self.frame, image=self.img)
        img_label.grid(row=1, column=1, padx=1, pady=(10, 150))
        #############################################################################################################################################################################################################
        # Image labels and yoga pose names
        img_cobra = Image.open("C:/aryaaa/arya's model(2)/deploying model/cobra pose.jpg")
        resized_img_cobra = img_cobra.resize((200, 200))
        self.img_cobra = ImageTk.PhotoImage(resized_img_cobra)
        img_label_cobra = tk.Label(self.frame, image=self.img_cobra)
        img_label_cobra.grid(row=4, column=0, padx=230, sticky='w', pady=30, columnspan=1)
        cobra_label = tk.Label(self.frame, text="COBRA POSE", font=("Times New Roman", 14, "bold"), bg="white", foreground="black")
        cobra_label.grid(row=3, column=0, padx=270, sticky='w', pady=10, columnspan=3)
        self.cobra_Button = tk.Button(self.frame, text="START", command=self.start_Cobra_pose)
        self.cobra_Button.grid(row=5, column=0, padx=300, sticky='w', pady=(10,100), columnspan=3)

        img_mountain = Image.open("C:/aryaaa/arya's model(2)/deploying model/mountain pose.jpg")
        resized_img_mountain = img_mountain.resize((200, 200))
        self.img_mountain = ImageTk.PhotoImage(resized_img_mountain)
        img_label_mountain = tk.Label(self.frame, image=self.img_mountain)
        img_label_mountain.grid(row=4, column=0, padx=5, pady=30, columnspan=4)
        mountain_label = tk.Label(self.frame, text="MOUNTAIN POSE", font=("Times New Roman", 14, "bold"), bg="white", foreground="black")
        mountain_label.grid(row=3, column=0, padx=0, pady=10, columnspan=5)
        self.mountain_Button = tk.Button(self.frame, text="START", command=self.start_mountain_pose)
        self.mountain_Button.grid(row=5, column=0, padx=0, pady=(10,100), columnspan=5)

        img_tree = Image.open("C:/aryaaa/arya's model(2)/deploying model/treepose.jpg")
        resized_img_tree = img_tree.resize((200, 200))
        self.img_tree = ImageTk.PhotoImage(resized_img_tree)
        img_label_tree = tk.Label(self.frame, image=self.img_tree)
        img_label_tree.grid(row=4, column=1, padx=230, pady=30, columnspan=2, sticky='e')
        tree_label = tk.Label(self.frame, text="TREE POSE", font=("Times New Roman", 14, "bold"), bg="white", foreground="black")
        tree_label.grid(row=3, column=1, padx=280, pady=10, columnspan=5,sticky='e')
        self.tree_Button = tk.Button(self.frame, text="START", command=self.start_tree_pose)
        self.tree_Button.grid(row=5, column=1, padx=300, pady=(10,100), columnspan=5,sticky='e')

        img_triangle = Image.open("C:/aryaaa/arya's model(2)/deploying model/triangle pose.jpg")
        resized_img_triangle = img_triangle.resize((200, 200))
        self.img_triangle = ImageTk.PhotoImage(resized_img_triangle)
        img_label_triangle = tk.Label(self.frame, image=self.img_triangle)
        img_label_triangle.grid(row=8, column=1, pady=30, sticky='w') 
        triangle_label = tk.Label(self.frame, text="TRIANGLE POSE", font=("Times New Roman", 14, "bold"), bg="white", foreground="black")
        triangle_label.grid(row=7, column=1, padx=10, pady=10, columnspan=1, sticky='w')
        self.triangle_Button = tk.Button(self.frame, text="START", command=self.start_triangle_pose)
        self.triangle_Button.grid(row=9, column=1, padx=80, sticky='w', pady=10, columnspan=1)

        img_warrior = Image.open("C:/aryaaa/arya's model(2)/deploying model/warrior-2.jpg")
        resized_img_warrior = img_warrior.resize((200, 200))
        self.img_warrior = ImageTk.PhotoImage(resized_img_warrior)
        img_label_warrior = tk.Label(self.frame, image=self.img_warrior)
        img_label_warrior.grid(row=8, column=0, padx=10, pady=30, columnspan=1)
        warrior_label = tk.Label(self.frame, text="WARRIOR 2 POSE", font=("Times New Roman", 14, "bold"), bg="white", foreground="black")
        warrior_label.grid(row=7, column=0, padx=2, pady=10, columnspan=1)
        self.warrior2_Button = tk.Button(self.frame, text="START", command=self.start_Warrior2_pose)
        self.warrior2_Button.grid(row=9, column=0, padx=2,  pady=10, columnspan=1)

        # Bind the configure event to the function that updates the scroll region
        self.frame.bind("<Configure>", self.on_configure)

        # Bind the mouse wheel event to scroll the canvas
        self.root.bind("<MouseWheel>", self._on_mousewheel)

    def on_configure(self, event):
        self.canvas.configure(scrollregion=self.canvas.bbox('all'))

    def _on_mousewheel(self, event):
        self.canvas.yview_scroll(int(-1 * (event.delta / 120)), "units")

################################################################################################################################################################################
    def call_Model(self):
        myModel = keras.models.load_model("C:\\aryaaa\\arya's model(2)\\MTP MODEL\\" + self.model_To_Select, compile=False)   
        mpDrawing = mp.solutions.drawing_utils  
        mpPose = mp.solutions.pose   
        print(mpPose.POSE_CONNECTIONS) 
        landmarksArray = []
        columnArray = []
        frame_size = 5

        headers = ['0_x', '0_y', '0_z', '0_vis', '1_x', '1_y', '1_z', '1_vis', '2_x', '2_y', '2_z', '2_vis', '3_x', '3_y', '3_z', '3_vis', '4_x', '4_y', '4_z', '4_vis', '5_x', '5_y', '5_z', '5_vis', '6_x', '6_y', '6_z', '6_vis', '7_x', '7_y', '7_z', '7_vis', '8_x', '8_y', '8_z', '8_vis', '9_x', '9_y', '9_z', '9_vis', '10_x', '10_y', '10_z', '10_vis', '11_x', '11_y', '11_z', '11_vis', '12_x', '12_y', '12_z', '12_vis', '13_x', '13_y', '13_z', '13_vis', '14_x', '14_y', '14_z', '14_vis', '15_x', '15_y', '15_z', '15_vis', '16_x', '16_y', '16_z', '16_vis', '17_x', '17_y', '17_z', '17_vis', '18_x', '18_y', '18_z', '18_vis', '19_x', '19_y', '19_z', '19_vis', '20_x', '20_y', '20_z', '20_vis', '21_x', '21_y', '21_z', '21_vis', '22_x', '22_y', '22_z', '22_vis', '23_x', '23_y', '23_z', '23_vis', '24_x', '24_y', '24_z', '24_vis', '25_x', '25_y', '25_z', '25_vis', '26_x', '26_y', '26_z', '26_vis', '27_x', '27_y', '27_z', '27_vis', '28_x', '28_y', '28_z', '28_vis', '29_x', '29_y', '29_z', '29_vis', '30_x', '30_y', '30_z', '30_vis', '31_x', '31_y', '31_z', '31_vis', '32_x', '32_y', '32_z', '32_vis']

        headersLength = len(headers)
        columnArray = []
        for i in range(0, headersLength):
            columnArray.append(i)
        columnArray = []
        for i in range(0, headersLength):
            columnArray.append(i)
 
        with mpPose.Pose(min_detection_confidence=0.8, min_tracking_confidence=0.8) as pose:
            cap = cv2.VideoCapture(0)
            frame_buffer = []
            while cap.isOpened():  # Start the loop to process frames from the webcam
                landmarksArray = []
                ret, frame = cap.read()
                frame = cv2.flip(frame, 1)
                image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                image.flags.writeable = False
                results = pose.process(image)
                image.flags.writeable = True
                image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

                try:
                    capturedLandmarks = results.pose_world_landmarks.landmark
                    for i in range(0, len(headers)):
                        landmarksArray.append(capturedLandmarks[i].x)
                        landmarksArray.append(capturedLandmarks[i].y)
                        landmarksArray.append(capturedLandmarks[i].z)
                        landmarksArray.append(capturedLandmarks[i].visibility)
                except:
                    pass

                landmarksArray = np.array(landmarksArray)

                if len(landmarksArray) == 132:  # Check if landmarksArray has the expected number of features
                    frame_buffer.append(landmarksArray.copy())

                if len(frame_buffer) >= frame_size:
                    # Concatenate the frames to create a sequence
                    input_sequence = np.array(frame_buffer).reshape(1, frame_size, 132)
                    result = myModel(input_sequence)
                    print("The result is ", result)
                    resultIndex = np.argmax(result)

                    if resultIndex == 0:
                        Pose_Names ="Normal"

                    else:
                        Pose_Names= self.model_To_Select

                    cv2.putText(image, str(Pose_Names), (20, 50), cv2.FONT_HERSHEY_TRIPLEX, 0.8, (180, 0, 100), 2, bottomLeftOrigin=False)

                    mpDrawing.draw_landmarks(image, results.pose_landmarks, mpPose.POSE_CONNECTIONS,
                                            mpDrawing.DrawingSpec(color=(0, 0, 255), thickness=2, circle_radius=4),
                                            mpDrawing.DrawingSpec(color=(0, 255, 0), thickness=2, circle_radius=0))

                    cv2.imshow('Pose Classification', image)
                    
                    frame_buffer = frame_buffer[1:]
                    
                if cv2.waitKey(10) & 0xFF == ord('q'):
                    break

        cap.release()
        cv2.destroyAllWindows()



    def start_mountain_pose(self):
        self.model_To_Select = "Mountain Pose"
        self.call_Model()
    
    def start_triangle_pose(self):
        self.model_To_Select = "Triangle Pose"
        self.call_Model()
    
    def start_tree_pose(self):
        self.model_To_Select = "Tree Pose"
        self.call_Model()
    
    def start_Warrior2_pose(self):
        self.model_To_Select = "Warrior2 Pose"
        self.call_Model()
    
    def start_Cobra_pose(self):
        self.model_To_Select = "Cobra Pose"
        self.call_Model()
###########################################################################################################################################################################################
  
if __name__ == "__main__":
    root = tk.Tk()
    app = YogifyApp(root)
    root.mainloop()


frozenset({(15, 21), (16, 20), (18, 20), (3, 7), (14, 16), (23, 25), (28, 30), (11, 23), (27, 31), (6, 8), (15, 17), (24, 26), (16, 22), (4, 5), (5, 6), (29, 31), (12, 24), (23, 24), (0, 1), (9, 10), (1, 2), (0, 4), (11, 13), (30, 32), (28, 32), (15, 19), (16, 18), (25, 27), (26, 28), (12, 14), (17, 19), (2, 3), (11, 12), (27, 29), (13, 15)})
The result is  tf.Tensor([[9.9997813e-01 1.1662494e-04]], shape=(1, 2), dtype=float32)
The result is  tf.Tensor([[9.9998873e-01 6.6971937e-05]], shape=(1, 2), dtype=float32)
The result is  tf.Tensor([[9.9999249e-01 4.8743812e-05]], shape=(1, 2), dtype=float32)
The result is  tf.Tensor([[9.9999368e-01 4.2852003e-05]], shape=(1, 2), dtype=float32)
The result is  tf.Tensor([[9.9999517e-01 3.4238277e-05]], shape=(1, 2), dtype=float32)
The result is  tf.Tensor([[9.9999720e-01 2.0713578e-05]], shape=(1, 2), dtype=float32)
The result is  tf.Tensor([[9.9999833e-01 1.3027103e-05]], shape=(1, 2), dtype=float32)
The result is  tf.Tensor([[9.9999887e-01 9.274